baseURL = "http://www.slizaa.org/"
languageCode = "de-DE"
title = "Slizaa"

relativeURLs = true

enableGitInfo = true 

pygmentsStyle = "tango"

[taxonomies]
  tag = "tags"
  category = "categories"
  documentationCategory = "documentationCategories"
  developmentCategory = "developmentCategories"
  communityCategory = "communityCategories"

